### ISSUE TITLE
`venv/Scripts/activate` not working in setup -- change to venv activate line

### ISSUE THREAD

**Issue by ltjds** [xhlulu/dash_pivottable#1]
First of all, this thing is *AWESOME*!! Thank you so much!!

Right now, you have the setup commands to be:

```
$ git clone https://github.com/xhlulu/dash_pivottable.git
$ cd dash_pivottable
$ virtualenv venv
$ venv/Scripts/activate
$ pip install -r requirements.txt

$ python usage.py
```

BUT, I had some issues with this, and it wasn't getting past the third step. In the end, I needed to run these instead:

```
$ git clone https://github.com/xhlulu/dash_pivottable.git
$ cd dash_pivottable
$ virtualenv venv
$ source venv/bin/activate    # Just change this line a bit
$ pip install -r requirements.txt

$ python usage.py

# Then, to deactivate, just
$ deactivate
```
And, of course for future uses:

```
$ cd dash_pivottable
$ source venv/bin/activate
$ python usage.py

# Do stuff
$ deactivate
```
I'm running on MacOS with Mojave, vers 10.14.3.

Thanks again!

**Comment by xhlulu** [comment]
Oops, Haven't realized this since I'm not using linux haha. Could you submit a PR to change this? Thanks!
