### ISSUE TITLE
Is it possible to export to excel?

### ISSUE THREAD

**Issue by happyshows** [xhlulu/dash_pivottable#5]
Hi,

This is handy and end user will probably ask for how to export the pivoted data. Is export to excel an option? Or it depends on react-pivotable to implement certain interface?

**Comment by xhlulu** [comment]
It's solely based on react-pivottable feature wise. You can create a callback that lets you retrieve the data inside the current view (by filtering your original data using the rows and cols that are currently selected; pretty easily done in pandas). 

Then once you have that filtered dataframe, you can export it into CSV, then use [the method discussed in this thread](https://community.plot.ly/t/allowing-users-to-download-csv-on-click/5550/2) to let the user download the file.

**Comment by happyshows** [comment]
Thanks.

**Comment by rdkbruce** [comment]
@happyshows Were you able to achieve the file export? If yes, could you please outline how you did it?
thanks
