### ISSUE TITLE
Option to show only table/chart

### ISSUE THREAD

**Issue by syu6882** [xhlulu/dash_pivottable#8]
Is it possible hide the pivot table/UI controls, keeping only the pivot table/chart? I saw [Nicholas's reply](https://github.com/plotly/react-pivottable/issues/10#issuecomment-353881833) to the same question on the react-pivottable project but after changing `<PivotTableUI ... />` to `<PivotTable ... />` in PivotTable.react.js and generating a new PivotTable.py, the web page fails to load.

**Comment by abogaard** [comment]
Hi @syu6882 did you find a solution here?

**Comment by abogaard** [comment]
For anyone interested, my solution for this was with css:

`.PTnoUI .pvtHorizList  {
    display: none !important;
}

.PTnoUI .pvtVertList  {
    display: none !important;
}

.PTnoUI .pvtRenderers {
    display: none !important;
}

.PTnoUI .pvtVals {
    display: none !important;
}`

**Comment by Qua111** [comment]
@abogaard Can you explain me where you added this css? I tried adding it to my global dash .css file, but to no effect. I can't find any specific css files related to the react/dash pivottable. Thanks!

**Comment by abogaard** [comment]
Hi @Qua111 I added this into the typography.css file in the assets directory as specified here: [https://dash.plot.ly/external-resources](https://dash.plot.ly/external-resources) Does this help?

Finding the relevant css classes can be aided by picking through the original plotly pivottable repo. 

I strongly recommend using your browser's developer tools to help with this.
